name: Build

on:
  pull_request: {}
  push: { branches: [main] }

jobs:
  build:
    name: ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneOSX # Build a macOS standalone (Intel 64-bit).
          - StandaloneWindows # Build a Windows standalone.

    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true

      # Get license
      - name: Unity License Activation (XRTK)
        uses: XRTK/activate-unity-license@v5
        with:
          # Unity Username
          username: keylexiao@gmail.com
          # Unity Password
          password: Xiaonian520!

      # Cache
      - name: Cache
        uses: actions/cache@v2
        with:
          path: HexEditorProject/Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-

      
      # Build
      - name: Build
        uses: game-ci/unity-builder@v4.2.3
       # env:
      #    UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          projectPath: HexEditorProject

      # Upload Build
      - name: Upload Build
        uses: actions/upload-artifact@v2
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: HexEditorProject/build/${{ matrix.targetPlatform }}
