name: Build

on:
  pull_request: {}
  push: { branches: [main] }

jobs:
  build:
    name: ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneOSX # Build a macOS standalone (Intel 64-bit).
          - StandaloneWindows # Build a Windows standalone.

    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true

      - uses: xrtk/unity-setup@v7
        with:
          build-targets: ${{ matrix.build-target }}

        # Activates the installation with the provided credentials
      - uses: xrtk/activate-unity-license@v5.1
        with:
          # Required
          username: keylexiao@gmail.com
          password: Xiaonian520!
          # Optional
          license-type: 'Professional' # Chooses license type to use [ Personal, Professional ]
          serial: ${{ secrets.UNITY_SERIAL }} # Required for pro/plus activations
          auth-key: ${{ secrets.UNITY_2FA_KEY }} # required for personal activations
            

      # Cache
      - name: Cache
        uses: actions/cache@v2
        with:
          path: HexEditorProject/Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-

      
      # Build
      - name: Build
        uses: game-ci/unity-builder@v4.2.3
       # env:
      #    UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          projectPath: HexEditorProject

      # Upload Build
      - name: Upload Build
        uses: actions/upload-artifact@v2
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: HexEditorProject/build/${{ matrix.targetPlatform }}
